name: InfectedPlugin
main: me.ColdBloodedCoders.InfectedPlugin.InfectedPlugin
version: 2.3
description: Plugin for the BitchCraft server.
authors: [PieGuy7896, hockeyfan360]

commands:
  bar:
    description: Broadcast a preset message to the server
    usage: /<command>
    
  test:
    description: Is the server lagging?
    usage: /<command>
